// SPDX-License-Identifier: Apache-2.0
// The readable classic script is the source of truth; generate a native ESM entry.
import { readFile, writeFile } from "node:fs/promises";
const root = new URL("../", import.meta.url);
const source = await readFile(new URL("paper-curl.js", root), "utf8");
const start = source.indexOf("  /* A welded");
const end = source.lastIndexOf("  global.PaperCurl = PaperCurl;");
if (start < 0 || end < start) throw new Error("Core module boundaries changed");
const module =
  source.slice(0, source.indexOf("(function (global)")) +
  "// Generated by scripts/build-module.mjs; edit paper-curl.js.\n" +
  source.slice(start, end).replace(/^  /gm, "") +
  "export { PaperCurl };\nexport default PaperCurl;\n";
await writeFile(new URL("paper-curl.mjs", root), module);
